<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Общий-вывод" data-toc-modified-id="Общий-вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Общий вывод</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Этап-1.-Изучение-и-предобработка-данных." data-toc-modified-id="Этап-1.-Изучение-и-предобработка-данных.-5.0.1"><span class="toc-item-num">5.0.1&nbsp;&nbsp;</span>Этап 1. Изучение и предобработка данных.</a></span></li><li><span><a href="#Этап-2.-Умножение-матриц." data-toc-modified-id="Этап-2.-Умножение-матриц.-5.0.2"><span class="toc-item-num">5.0.2&nbsp;&nbsp;</span>Этап 2. Умножение матриц.</a></span></li><li><span><a href="#Этап-3.-Алгоритм-преобразования." data-toc-modified-id="Этап-3.-Алгоритм-преобразования.-5.0.3"><span class="toc-item-num">5.0.3&nbsp;&nbsp;</span>Этап 3. Алгоритм преобразования.</a></span></li></ul></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

###### Цель исследования:
Защитить данные клиентов страховой компании «Хоть потоп».

###### Ход исследования:
1. Открыть и изучить предоставленные данные и подготовить их к исследованию.
2. Теоретически проверить, изменится ли качество линейной регрессии при умножении признаков на обратимую матрицу. Обосновать решение.
3. Предложите алгоритм преобразования данных для решения задачи.
4. Запрограммировать этот алгоритм. Проверить, что качество линейной регрессии не отличается до и после преобразования (используя метрику R2).
6. Сделать вывод. 

## Загрузка данных

1. Импортируем библиотеки, которые понадобятся в ходе работы.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

2. Загрузим датасет и изучим информацию о нем.

In [2]:
data = pd.read_csv('/datasets/insurance.csv')
print(data.head(10))
print(data.info())
print(data.describe())

   Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
5    1     43.0   41000.0            2                  1
6    1     39.0   39700.0            2                  0
7    1     25.0   38600.0            4                  0
8    1     36.0   49700.0            1                  0
9    1     32.0   51700.0            1                  0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи

В целом данные выглядят адекватно(информация в таблице содержится согласно документации), пропусков не обнаружено. Типы данных тоже в норме. Проверим на явные дубликаты. 

In [3]:
data.duplicated().sum()

153

В ходе проверки обнаружены дубликаты. Полное совпадение данных очень подозрительно и, скорее всего, маловероятно, поэтому считаю, что дубликаты лучше удалить.

In [4]:
data.drop_duplicates()
data.duplicated().sum()

153

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Вывод: В ходе первичного исследования данных были обнаружены полные дубликаты. Строки с дублирующимися данными были удалены. Масштабирование признаков и проверку на баланс классов проводить не будем, т.к. нет задачи добиться максимального качества модели, нужно лишь проверить влияние на качество модели линейной регресии умножения признаков на обратимую матрицу. В остальном данные готовы для дальнейших исследований.

## Умножение матриц

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Не изменится

**Обоснование:** В данном случае, нам нужно доказать, что если матрицу признаков (X) умножить на обратимую матрицу (P), то качество линейной регрессии не изменится, а значит 
$$
a = a_P = Xw = Xw_P
$$


Т.к. $ a = Xw = X(X^T X)^{-1} X^T y $ , нужно доказать, что $ X(X^T X)^{-1} X^T y = XP((XP)^T XP)^{-1} (XP)^T y $


Для этого еще раз выпишем формулу, в которой мы домножили матрицу признаков (Х) на обратимую мартицу (Р):
$$
XP((XP)^T XP)^{-1} (XP)^T y = XP(X^T P^T XP)^{-1} X^T P^T y
$$

мы знаем, что по свойствам матриц, произведение матрицы $P$ на обратную мартицу $P^{-1}$будет равно единичной мартице Е. А при умножении матрицы Х на единичную получится эта же матрица Х. Поэтому вынесем за скобки значения, которые мы сможем сократить:
$$
XP(X^T P^T XP)^{-1} X^T P^T y = XPP^{-1} (X^T X)^{-1} (P^T)^{-1} X^T P^T y = 
= XE(X^T X)^{-1} X^T E y = X(X^T X)^{-1} X^T y
$$

Таким образом мы получили:
$$
XP((XP)^T XP)^{-1} (XP)^T y = X(X^T X)^{-1} X^T y = Xw = a
$$

При умножении признаков на обратимую матрицу параметры линейной регресии не изменятся, соответственно не изменится и качество. 

## Алгоритм преобразования

**Алгоритм**

Для того, чтобы защитить данные клиентов страховой компании «Хоть потоп», мы зашифруем их, умножив на произвольную обратимую квадратную матрицу. Важно будет учесть следующие моменты:
- произвольная матрица должна содержать количество строк равное количеству признаков в нашей таблице;
- необходимо проверить, является ли случайная матрица обратимой, во избежание конфузов.

**Обоснование**

В предыдущем пункте мы уже доказали, что умножение признаков на обратимую матрицу никак не повлияет на качество модели линейной регрессии, поэтому можем приступать к шифрованию данных и проверки этоого алгоритма.

## Проверка алгоритма

1. Разделим нашу таблицу на признаки и целевой признак (столбец Страховые выплаты)

In [6]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']
print(features.shape)
print(target.shape)

(5000, 4)
(5000,)


2. Разделим данные на обучающую и тестовую выборки

In [7]:
features_train, features_test, target_train, target_test = train_test_split(features, target, 
                                                                            test_size=0.25, random_state=12345) 

In [8]:
print(features_train.shape)
print(target_train.shape)

(3750, 4)
(3750,)


In [9]:
print(features_test.shape)
print(target_test.shape)

(1250, 4)
(1250,)


3. Обучим модель на исходных данных и вычислим показатель качества модели, используя метрику R2

In [10]:
model = LinearRegression()
model.fit(features_train, target_train)
predictions = model.predict(features_test)
print('Метрика R2 исходных данных:', r2_score(predictions, target_test))

Метрика R2 исходных данных: -0.2869270212348396


Качество модели получилось очень низкое, но в данном случае, нам это не так важно. Наша цель - убедиться, что при шифровке данных, метрика не изменится.

4. Подготовим данные для шифрования:

In [11]:
# преобразуем признаки в матрицу
features_matrix = features.values
features_matrix

array([[1.00e+00, 4.10e+01, 4.96e+04, 1.00e+00],
       [0.00e+00, 4.60e+01, 3.80e+04, 1.00e+00],
       [0.00e+00, 2.90e+01, 2.10e+04, 0.00e+00],
       ...,
       [0.00e+00, 2.00e+01, 3.39e+04, 2.00e+00],
       [1.00e+00, 2.20e+01, 3.27e+04, 3.00e+00],
       [1.00e+00, 2.80e+01, 4.06e+04, 1.00e+00]])

In [12]:
# Создадим рандомную квадратную матрицу с количеством строк, равным количеству признаков
random_matrix = np.random.normal(size=(4, 4))
random_matrix

array([[-0.05245211, -0.69005572, -0.42068942, -0.29179579],
       [ 1.01176823, -1.36426529, -0.07305482,  0.19985994],
       [-1.20472425,  1.76693156, -0.06930627,  1.35018487],
       [-2.19873042,  1.02589579,  0.95080617, -1.70987103]])

In [13]:
# Проверим полученную матрицу на обратимость (если матрица не обратима, код выдаст ошибку)
np.linalg.inv(random_matrix)

array([[-0.76551666, -0.73844803, -0.61356109, -0.44016918],
       [-0.50677967, -1.2091372 , -0.36593506, -0.34380481],
       [-1.38718327,  1.38556237,  0.2033495 ,  0.55925392],
       [-0.09104826,  0.99457831,  0.68250186,  0.08588223]])

In [14]:
# Умножим матрицу признаков на сгенерированную случайную матрицу
features_matrix_encoded = np.dot(features_matrix, random_matrix)
features_matrix_encoded

array([[-59715.0913194 ,  87584.20619696,  -3440.05634496,
         66975.36197809],
       [-45735.17876484,  67081.66886352,  -2636.04814567,
         51314.50862007],
       [-25269.86790113,  37065.9990064 ,  -1457.55035378,
         28359.67813855],
       ...,
       [-40824.31405802,  59873.74627256,  -2349.04218887,
         45771.84443722],
       [-39378.87260809,  57751.0357135 ,  -2265.49065238,
         44150.02065026],
       [-48885.72608648,  71699.55763153,  -2815.35016202,
         54821.09999875]])

In [15]:
# Преобразуем полученную зашифрованную матрицу в DataFrame
features_encoded = pd.DataFrame(features_matrix_encoded)
features_encoded.head()

0             1            2             3
0 -59715.091319  87584.206197 -3440.056345  66975.361978
1 -45735.178765  67081.668864 -2636.048146  51314.508620
2 -25269.867901  37065.999006 -1457.550354  28359.678139
3 -50220.151414  73654.448153 -2889.704185  56303.486257
4 -31415.025779  46078.024157 -1811.359988  35245.129303

In [16]:
# Разделим зашифрованные данные на обучающую и тестовую выборки, в той же пропорции, что и делили исходные данные
# целевой признак у нас уже подготовлен
features_encoded_train, features_encoded_test = train_test_split(features_encoded, test_size=0.25, 
                                                                 random_state=12345) 

In [17]:
print(features_encoded_train.shape)
print(features_encoded_test.shape)

(3750, 4)
(1250, 4)


In [18]:
# Обучим модель на преобразованных данных и вычислим показатель качества модели, используя метрику R2
model_encoded = LinearRegression()
model_encoded.fit(features_encoded_train, target_train)
predictions_encoded = model_encoded.predict(features_encoded_test)
print('Метрика R2 преобразованных данных:', r2_score(predictions_encoded, target_test))

Метрика R2 преобразованных данных: -0.2869270212305002


In [19]:
# Сравним полученные метрики
print('Метрика R2 исходных данных:', r2_score(predictions, target_test))
print('Метрика R2 преобразованных данных:', r2_score(predictions_encoded, target_test))

Метрика R2 исходных данных: -0.2869270212348396
Метрика R2 преобразованных данных: -0.2869270212305002


Вывод: Значение метрики качества модели - R2 - совпало в исходных и преобразованных данных(с небольшой погрешностью). На практике мы получили тот же результат, как и в теоретических расчетах выше. 

## Общий вывод

#### Этап 1. Изучение и предобработка данных.
В ходе данного этапа был открыт файл и изучены данные в нем. Были удалены, обнаруженные в ходе изучения, дубликаты. В остальном данные соответствовали документации.


#### Этап 2. Умножение матриц.
В ходе этого этапа математически было доказано отсутствие влияния на качество модели линейной регресии умножения признаков на обратимую матрицу. 

#### Этап 3. Алгоритм преобразования.

Был предложен алгоритм преобразования - умножение признаков на случайную обратимую квадратную матрицу. А так же этот алгоритм был проверен на практике. В результате метрики R2 у модели, обученной на исходных данных, и у модели, обученной на преобразованных данных, получилась равны.

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [ ]  Весь код выполняется без ошибок
- [ ]  Ячейки с кодом расположены в порядке исполнения
- [ ]  Выполнен шаг 1: данные загружены
- [ ]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [ ]  Указан правильный вариант ответа
    - [ ]  Вариант обоснован
- [ ]  Выполнен шаг 3: предложен алгоритм преобразования
    - [ ]  Алгоритм описан
    - [ ]  Алгоритм обоснован
- [ ]  Выполнен шаг 4: алгоритм проверен
    - [ ]  Алгоритм реализован
    - [ ]  Проведено сравнение качества моделей до и после преобразования